Решение двух задач
js-tasks-ru/vue-20230120_ulyana0 pull request #3
Opened 2023-01-30 08:51 UTC by EkzLin

2023-01-30 08:53 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-31 07:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-01 04:38 UTC, ShGKme requested changes
В `01-basics/03-MarkedList` требуется сделать такое вычисляемое свойство, которое помогает сразу выводить маркированный список.

2023-02-01 04:38 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
> +      <button type="button" @click="counter ++">{{counter}}</button>
У текстовой интерполяции обычно принято добавлять пробелы в скобках: `{{ counter }}`

2023-02-01 04:38 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          <li v-for="item in emails" :class="{marked: this.search && filteredArray.includes(item) }">{{ item }}</li>
Код шаблона выполняется в области видимости экземпляра компонента, `this` не требуется.

2023-02-01 04:38 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +        });
Первое присваивание в `this.title` результата функции `fetchMeetupById` - лишнее.

Так сначала в `this.title` хранится promise от асинхронной функции, а потом заголовок. Это очень разные значение, будет сложно работать, если в переменной лежит то одно, то другое. А этот промис всё равно не используется в решении.

2023-02-01 04:38 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
На вебинаре мы использовали вычисляемое свойство для подготовки **отфильтрованных** данных и дальнейшего вывода отфильтрованного списка. Но здесь - другая задача. Здесь требуется вывести **ВСЕ** данные, но некоторые элементы - **отметить** маркировкой.

В вычисляемом свойстве нужно вернуть что-то, что поможет вывести список с не только самой почтой, но и классом с маркировкой при необходимости.

2023-02-01 04:38 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          <li v-for="item in emails" :class="{marked: this.search && filteredArray.includes(item) }">{{ item }}</li>
В текущем решении список выводится следующим образом:
1. Вычисляется список отфильтрованных почт
   - В процессе этого вычисления перебирается каждая почта и поиском подстроки проверяется, не подходит ли почта под фильтр. **На самом деле уже на этом шаге на самом деле была проверена каждая почта.** Но результат этой проверки нельзя напрямую использовать.
2. Затем почты снова перебираются уже для вывода на странице.
   1. Во время вывода **каждой** почты требуется проверить, не подходит ли она под условие маркировки.
   2. Для этого снова перебирается весь массив отфильтрованных почт, чтобы проверить, а не находится ли текущая почта в списке успешно прошедших проверок. На самом первом пункте каждая почта уже была проверена. Но здесь снова проверяется в худшем случае весь список почт, чтобы узнать, как прошла эта проверка.

Второй пункт происходит при каждом повторном рендеринге, даже если не менялись условия поиска.

В результате получается квадратичная сложность линейного вывода. Условно, чтобы вывести 100 строк, выполняется 10 000 действий. Это больше, чем если бы каждая почта просто проверялась на соответствие поиска прямо во время вывода.

Вычисляемое свойство должно быть таким, чтобы с ним во время вывода можно было сразу знать, промаркирована текущая выводящаяся почта или нет. Без запуска полного перебора массива.

2023-02-01 04:39 UTC, ShGKme commented
PR - это запрос на вливание одной ветки в другую.

В данном случае запрос на вливание ветки мастер вашего репозитория (форка) в ваш задачник.
Когда вы добавляете новый коммит в мастер, он попадает всё в ту же ветку, которая сейчас находится в запросе на слияние, по этому коммит попадает в тот же PR.

По этой причине не нужно закрывать и создавать новый PR при добавлении коммитов в решения (обновлении решения, добавления новых решений и т.д.). Новый созданный PR - точно такой же, как и старый закрытый. На слияние той же самой ветки в ту же самую, что и в прошлом PR.

2023-02-01 13:00 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-01 18:30 UTC, ShGKme approved these changes
Все задачи приняты, всё отлично

2023-02-01 18:30 UTC, merged